##################################################################################
# Cloudify Package Installer Plugin.
##################################################################################

plugins:
  package_installer:
    executor: host_agent
    source: https://github.com/kemiz/cloudify-package-installer-plugin/archive/master.zip

node_types:

  cloudify.nodes.PackageInstaller:
    derived_from: cloudify.nodes.SoftwareComponent
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: package_installer.package_installer_plugin.tasks.install
          inputs:
            install_from_repo:
              default: True
              type: boolean
              description: >
                Install from repository or URL
            package_list:
              description: >
                Provide a list of RPM or DEB file URLs to install