##################################################################################
# Cloudify Package Installer Plugin.
##################################################################################

plugins:
  package_installer:
    executor: host_agent
    source: https://github.com/kemiz/cloudify-package-installer-plugin/archive/3.2-plugin-aggregator-test.zip
  elasticsearch:
    executor: host_agent
    source: https://github.com/kemiz/cloudify-elasticsearch-plugin/archive/3.2.zip

node_types:

  cloudify.nodes.PackageInstaller:
    derived_from: cloudify.nodes.SoftwareComponent
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: package_installer.package_installer_plugin.tasks.install
          inputs:
            service_to_install:
              description: >
                Name of the service to install